openasmat_django/calendrier/urls.py
from django.urls import path

from . import views

app_name = 'Calendrier'
urlpatterns = [
    # /calendrier
    path('', views.index, name='index'),
    # /calendrier/2018/05
    path('<int:annee>/<int:mois>', views.mois, name='mois'),
    path('ajouter', views.ajouterDate, name='ajouterDate'),
    path('sauver', views.sauverDate, name='sauverDate'),
]

openasmat_django/openasmat_django/urls.py
from django.contrib import admin
from django.urls import include, path

import calendrier as Calendrier

urlpatterns = [
    path('calendrier/', include('calendrier.urls')),
    path('contrat/', include('contrat.urls')),
    path('tiers/', include('tiers.urls')),
    path('admin/', admin.site.urls),
    path('', Calendrier.views.index, name='index'),
]

openasmat_django/tiers/urls.py
from django.urls import path

from . import views

app_name = 'Tiers'
urlpatterns = [
    # /tiers
    path('', views.index, name='Index'),
    path('connexion', views.verifierIdentification, name='login'),
    path('deconnexion', views.deconnexion, name='logout'),
    # /tiers/123
    #path('<int:idtiers>', views.tiers, name='tiers'),
]

openasmat_django/calendrier/models.py
from django.db import models

import datetime
import calendar

import locale
from jours_feries_france.compute import JoursFeries
from vacances_scolaires_france import SchoolHolidayDates

class Calendrier(models.Model):
    Contrat = models.ForeignKey(
        'contrat.Contrat',
        on_delete=models.PROTECT,
    )
    Type = models.ForeignKey(
        'TypeTravail',
        on_delete=models.PROTECT,
    )
    date = models.DateField('date')
    heuresRealise = models.DecimalField(max_digits=4, decimal_places=2)
    indemEntretien = models.BooleanField(default=False)
    indemRepas = models.BooleanField(default=False)
    indemGouter = models.BooleanField(default=False)
    indemKm = models.DecimalField(max_digits=4, decimal_places=1, blank=True, null=True)
    valideRepresentantLegal = models.BooleanField(blank=True, null=True)
    valideAsmat = models.BooleanField(blank=True, null=True)
    class Meta:
        db_table = 'calendrier'
        get_latest_by = 'date'
        ordering = ('date',)
        unique_together = ('date','Contrat','Type')

    def __str__(self):
        return "%s (%s) %sh - E:%s"% (self.date, self.Type, self.heuresRealise, self.indemEntretien)

    def getJoursMois(Annee,Mois):
        """
        getJoursMois(Annee,Mois)
        Renvois les jours du Mois
        """
        locale.setlocale(locale.LC_ALL, '')
        joursFerier = JoursFeries.for_year(Annee).values()
        SchoolHolidayDatesObject = SchoolHolidayDates()
        weekend = ['0','6']
        datesMois = [False]
        # (datetime.date(Annee,Mois,1) + datetime.timedelta(days=x) \
        for j in range(1,calendar.monthrange(Annee,Mois)[1]+1):
            jour = datetime.date(Annee,Mois,j)
            datesMois.append({
                "date":jour.strftime('%d %A'),
                "estWeekend":(jour.strftime('%w') in weekend),
                "estFerie":(jour in joursFerier),
                "estVacancesZoneA":SchoolHolidayDatesObject.is_holiday_for_zone(jour, 'A'),
                "estVacancesZoneB":SchoolHolidayDatesObject.is_holiday_for_zone(jour, 'B'),
                "estVacancesZoneC":SchoolHolidayDatesObject.is_holiday_for_zone(jour, 'C'),
                "contrats":[],
            })
        return datesMois

    def getEnregistrementMois(ListIdContrats,Annee,Mois):
        """
        getEnregistrementMois(ListIdContrats,Annee,Mois)
        Renvois les contrat du mois
        avec :
         - ListIdContrats : laliste des id des contrats a prendre en compte
         - Annee,Mois : l'année et le mois à prendre en compte
        """
        return Calendrier.objects \
            .filter(Contrat__in=ListIdContrats) \
            .filter(date__year=Annee,date__month=Mois)

    def getTotalMois(QuerySetIdContrats,Annee,Mois):
        """
        getTotalMois(ListIdContrats,Annee,Mois)
        Renvois pour un mois:
        - total des heures rémunérées
        - total des heures par catégorie
        - nombre d'indemnité d'entretien
        - nombre d'indemnité de repas
        - nombre d'indemnité de gouter
        - total des indemnité kilometrique
        """
        total={}
        for Contrat in QuerySetIdContrats:
          QuerySetMois = Calendrier.objects \
                  .filter(Contrat__id=Contrat.id) \
                  .filter(date__year=Annee,date__month=Mois)
          total[Contrat.id]={
              'nom':Contrat,
              'couleur':Contrat.couleur,
              'total':QuerySetMois.aggregate(
                      HeuresRemunere=models.Sum('heuresRealise'),
                      IndemKm=models.Sum('indemKm')
                  ),
              'nbIndemEntretien':QuerySetMois.filter(indemEntretien=True).count(),
              'nbIndemRepas':QuerySetMois.filter(indemRepas=True).count(),
              'nbIndemGouter':QuerySetMois.filter(indemGouter=True).count(),
          }
        return total

    def moisSuivant(annee, mois):
      suivantAnnee = annee
      suivantMois = mois + 1
      if mois == 12:
          suivantMois = 1
          suivantAnnee = annee +1
      return suivantAnnee, suivantMois
      
    def moisPrecedent(annee, mois):
      precedentAnnee = annee
      precedentMois = mois - 1
      if mois == 1:
          precedentMois = 12
          precedentAnnee = annee - 1
      return precedentAnnee, precedentMois

class TypeTravail(models.Model):
    nom = models.CharField(max_length=30)
    sigle = models.CharField(max_length=3)
    description = models.CharField(max_length=300, blank=True, null=True)

    def __str__(self):
        return "%s"% (self.sigle)

openasmat_django/calendrier/views.py
# import Django
from django.shortcuts import render
from django.shortcuts import HttpResponse, HttpResponseRedirect, reverse
from django.shortcuts import get_object_or_404
from django.http import Http404
# authentification
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

# les models openasmat
from contrat.models import Contrat
from .models import Calendrier, TypeTravail
from tiers.models import *

# import python général
import datetime

@login_required(login_url='/tiers')
def index(request):
    aujourdui=datetime.datetime.now()
    context={
        'message':"",
        'Annee':aujourdui.year,
        'Mois':aujourdui.month,
    }
    return render(request, 'calendrier/index.html', context)

@login_required(login_url='/tiers')
def mois(request,annee,mois):
    if mois < 1 or mois > 12:
        raise Http404("mois non reconnu")
    Contrats=Contrat.get(request.user.id, annee, mois)
    if Contrats.count()<1:
        context={
            'message':"Pasde contrat"
        }
        return HttpResponseRedirect(reverse('Contrat:index'),context)
# on récupère les données du mois
    try:
        ActiviteeJours = Calendrier.getEnregistrementMois(Contrats,annee,mois)
    except Calendrier.DoesNotExist:
        raise Http404("Erreur 404")
# dates suivante et précédente
    suivantAnnee, suivantMois = Calendrier.moisSuivant(annee,mois)
    precedentAnnee, precedentMois = Calendrier.moisPrecedent(annee,mois)

# Ajouts des activitées pour chaque jour
    joursMois = Calendrier.getJoursMois(annee,mois)
    #listIdContrat = list(Contrats.values_list('id',flat=True))
    listIdContrat = {}
    for id, couleur in list(Contrats.values_list('id', 'couleur')):
      listIdContrat.setdefault(id, []).append(couleur)
    listIdContratJours={}
    for j in ActiviteeJours:
      # le jour du mois a traiter
      jour = int(float(j.date.strftime('%d')))
      
      # si le jour n'est pas dans la liste, on l'ajoute à la liste
      if jour not in listIdContratJours:
        listIdContratJours[jour]=[]
        nextIndex = 0
     
      for i in range(nextIndex, list(listIdContrat.keys()).index(j.Contrat.pk)):
        joursMois[ jour ]['contrats'].append({})
      
      # si le contrat n'a pas été traitéer pour ce jour
      if j.Contrat.pk not in listIdContratJours[jour]:
        joursMois[ jour ]['contrats'].append( {
            'contratId':j.Contrat.pk,
            'contratNom':j.Contrat,
            'heuresRealise':j.heuresRealise,
            'TypeSigle':j.Type.sigle,
            'TypeNom':j.Type.nom,
            'indemEntretien':j.indemEntretien,
            'indemRepas':j.indemRepas,
            'indemGouter':j.indemGouter,
            'indemKm':j.indemKm,
            'ContratCouleur':listIdContrat[j.Contrat.pk][0],
        })
        listIdContratJours[jour].append(j.Contrat.pk)
        nextIndex=list(listIdContrat.keys()).index(j.Contrat.pk)+1

    context = {
        'joursMois': joursMois,
        'sousTitre':datetime.date(annee,mois,1).strftime('%B %Y'),
        'mois':mois,
        'precedentMois':precedentMois,
        'suivantMois':suivantMois,
        'annee':annee,
        'precedentAnnee':precedentAnnee,
        'suivantAnnee':suivantAnnee,
        'utilisateur':request.user,
        'Contrats':Contrats,
        'listeTypeTravail': TypeTravail.objects.all(),
        'date':datetime.date(annee,mois,1),
        'total':Calendrier.getTotalMois(Contrats,annee,mois),
    }
    return render(request, 'calendrier/mois.html', context)

@login_required(login_url='/tiers')
def ajouterDate(request):
    '''
    Affiche le formulaire d'ajout de date
    '''
    date = datetime.date.today().isoformat()
    context = {
        'date': date,
        'listeTypeTravail': TypeTravail.objects.all(),
        'utilisateurId':request.user.id,
        'utilisateurNom':request.user.username,
        'Contrats':Contrat.getContrats(request.user.id),
    }
    return render(request, 'calendrier/ajouter.html', context)

@login_required(login_url='/tiers')
def sauverDate(request):
    '''
    Valide et enregistre la date
    '''
    acceptedParam={
        'contrat':'contrat',
        'typeTravail':'typeTravail',
        'date':'date',
        'heure':None,
        'indemEntretien':False,
        'indemRepas':False,
        'indemGouter':False,
        'indemKm':0,
        'valideRepresentantLegal': False,
        'valideAsmat': False,
    }
    try:
        for key, val in request.POST.items():
            if key in acceptedParam:
                if val=='on':
                    val=True;
                if val=='':
                    val=False;
                acceptedParam[key]=val

    except(KeyError):
        context = acceptedParam
        context['listeTypeTravail'] = TypeTravail.objects.all()
        context['Contrats'] = Contrat.getContrats(request.user.id)
        return render(request, 'calendrier/ajouter.html', context)
    else:
        date = Calendrier(
            Contrat = Contrat(id=acceptedParam['contrat']),
            Type = TypeTravail(id=acceptedParam['typeTravail']),
            date = acceptedParam['date'],
            heuresRealise = acceptedParam['heure'],
            indemEntretien = acceptedParam['indemEntretien'],
            indemRepas = acceptedParam['indemRepas'],
            indemGouter = acceptedParam['indemGouter'],
            indemKm = acceptedParam['indemKm'],
            valideRepresentantLegal = acceptedParam['valideRepresentantLegal'],
            valideAsmat = acceptedParam['valideAsmat'],
        )
        date.save()
        return HttpResponseRedirect(
            reverse('Calendrier:mois',
                kwargs={'annee':date.date[0:4],'mois':date.date[5:7]})
            )

openasmat_django/calendrier/templates/calendrier/ajouter.html
<h1 id="formAddDate">Ajouter une date</h1>
{% if error_message %}
  <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'Calendrier:sauverDate' %}" method="post">
{% csrf_token %}
    <label for="contrat">contrat</label>
    <select id="contrat" name="contrat">
    {% for contrat in Contrats %}
      <option value="{{ contrat.id }}">{{ contrat }}</option>
    {% endfor %}
    </select>
    <br>
    <label for="date">date</label>
    <input type="date" name="date" id="date" value="{{ date|date:"Y-m-d" }}">
    <br>
    <label for="typeTravail">type de travail</label>
    <select id="typeTravail" name="typeTravail">
{% for option in listeTypeTravail %}
      <option value="{{ option.id }}">{{ option.nom }}</option>
{% endfor %}
    </select>
    <br>
    <label for="heure">heure rémunéré</label>
    <input type="input" name="heure" id="heure" value="{{ heure }}">
    <br>
    <label for="indemEntretien">Indemnité d'entretien</label>
    <input type="checkbox" id="indemEntretien" name="indemEntretien"
    {% if indemEntretien %}selected{% endif %}>
    <br>
    <label for="indemRepas">Indemnité de repas</label>
    <input type="checkbox" id="indemRepas" name="indemRepas"
    {% if indemRepas %}selected{% endif %}>
    <br>
    <label for="indemGouter">Indemnité de gouter</label>
    <input type="checkbox" id="indemGouter" name="indemGouter"
    {% if indemGouter %}selected{% endif %}>
    <br>
    <label for="indemKm">Indemnité kilométrique</label>
    <input type="input" name="indemKm" id="indemKm" value="{{ indemKm }}">
    <br>
    <input type="submit" value="ajouter">
</form>

openasmat_django/calendrier/templates/calendrier/index.html
<p>{{ message }}</p>
<a href="{% url 'Calendrier:mois' Annee Mois %}">Voir le mois en cours</a><br>
<a href="{% url 'Tiers:Index'%}">identification</a>

openasmat_django/calendrier/templates/calendrier/mois.html
{% extends "base_menu.html" %}

{% block menuSegondaire %}
<a href="{% url 'Calendrier:mois' precedentAnnee precedentMois %}">
  Mois précédent ({{precedentMois}}/{{precedentAnnee}})
</a>
 |
<a href="{% url 'Calendrier:index' %}">Calendrier:index</a>
 |
<a href="{% url 'Calendrier:mois' suivantAnnee suivantMois %}">
  Mois suivant ({{suivantMois}}/{{suivantAnnee}})
</a>
{% endblock %}

{% block main %}
<h1>{{sousTitre}}</h1>

<h2>Contrat:</h2>
<ul>
{% for Contrat in Contrats %}
  <li style="--color:{{ Contrat.couleur }};" class="pastille">{{ Contrat }}</li>
{% endfor %}
</ul>

<ul class="calendrier">
{% for jour in joursMois %}
  {% if jour %}
  <li class="{% if jour.estWeekend %}weekend{% endif %}{% if jour.estFerie %} ferie{% endif %}">
    <span class="vacances">
      <span class="{% if jour.estVacancesZoneA %}zoneA{% endif %}"
      title="{% if jour.estVacancesZoneA %}Vacances zone A{% endif %}"></span>
      <span class="{% if jour.estVacancesZoneB %}zoneB{% endif %}"
      title="{% if jour.estVacancesZoneB %}Vacances zone B{% endif %}"></span>
      <span class="{% if jour.estVacancesZoneC %}zoneC{% endif %}"
      title="{% if jour.estVacancesZoneC %}Vacances zone C{% endif %}"></span>
    </span>
    <span class="date">{{ jour.date }}</span>
    {% for contrat in jour.contrats %}
    <span class="contrat pastille" id="contrat_{{contrat.contratId}}" style="--color:{{ contrat.ContratCouleur }};">
      {% if contrat.contratId %}
      <span class="heuresRealise">{{ contrat.heuresRealise }}h</span>
      <span class="TypeTravail" title="{{ contrat.TypeNom }}">{{ contrat.TypeSigle }}</span>
      <span class="indemnite entretien {{ contrat.indemEntretien }}"
        title="Indemnité entretien">E</span>
      <span class="idemnite repas {{ contrat.indemRepas }}"
        title="Indemnité de repas">R</span>
      <span class="idemnite gouter {{ contrat.indemGouter }}"
        title="Indemnité de gouter">G</span>
      <span class="idemnite kilometrique {% if contrat.indemKm > 0 %}True{% else %}False{% endif %}"
        title="Indemnité kilometrique">{{ contrat.indemKm|default:"-" }} km</span>
      {% endif %}
    </span>
    {% empty %}
    {% endfor %}
  </li>
  {% endif %}
{% endfor %}
{% for key, TotalContrat in total.items %}
  <li class="total pastille" style="--color:{{ TotalContrat.couleur }};">
    <span class="contrat">{{ TotalContrat.nom }}</span>
    <span class="heures">Heures rémunérées: {{ TotalContrat.total.HeuresRemunere }}h</span>
    <span class="idemnite entretien" title="Indemnité d'entretien">
      E: {{ TotalContrat.nbIndemEntretien }}
    </span>
    <span class="idemnite repas" title="Indemnité de repas">
      R: {{ TotalContrat.nbIndemRepas }}
    </span>
    <span class="idemnite gouter" title="Indemnité de gouter">
      G: {{ TotalContrat.nbIndemGouter }}
    </span>
    <span class="idemnite kilometrique" title="Indemnité kilometrique">
      {{ TotalContrat.total.IndemKm }} km
    </span>
  </li>
{% endfor %}
</ul>

{% include "calendrier/ajouter.html" %}
{% endblock main %}